repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace    # Essential for consistent whitespace
    -   id: end-of-file-fixer     # Essential for file formatting
    -   id: check-yaml            # Essential for YAML validation
    -   id: check-merge-conflict  # Essential for preventing merge issues
    -   id: detect-private-key    # Essential for security

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black                 # Essential for code formatting
        language_version: python3.9
        args:
        - --line-length=130

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8               # Essential for code quality
        args:
        - "--max-line-length=130"
        - "--ignore=F401,F541,F841,W605,E203,E402,E501,W503"
        - "--per-file-ignores=test_*.py:F401,E402"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy                 # Essential for type checking
        additional_dependencies:
        - types-requests
        - types-PyYAML
        args:
        - --ignore-missing-imports
        - --warn-return-any
        - --strict-optional
