name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not `main`
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Python (or other languages, adjust accordingly)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Change if you're using another language, like Node.js

      # Install dependencies
      - name: Install dependencies
        run: |
          make setup  # Run the 'setup' make target

      # Run the application (optional for CI, depends on your needs)
      - name: Run application
        run: |
          make run  # This is optional, you might not need to run it in CI/CD

  lint:
    runs-on: ubuntu-latest
    needs: setup  # Make sure 'setup' job is completed first

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make setup  # Ensure dependencies are installed

      - name: Run linters
        run: |
          make lint  # Run the 'lint' make target

  test:
    runs-on: ubuntu-latest
    needs: setup  # Make sure 'setup' job is completed first

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make setup  # Install dependencies

      - name: Run tests
        run: |
          make test  # Run the 'test' make target

  format:
    runs-on: ubuntu-latest
    needs: setup  # Ensure setup is done before formatting

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make setup  # Install dependencies

      - name: Run code formatting
        run: |
          make format  # Run the 'format' make target

  pre-commit:
    runs-on: ubuntu-latest
    needs: setup  # Ensure setup is done before pre-commit checks

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make setup  # Install dependencies

      - name: Run pre-commit checks
        run: |
          make pre-commit  # Run all checks via the 'pre-commit' make target

  release:
    runs-on: ubuntu-latest
    needs: [lint, test, format]  # Make sure linting, testing, and formatting are done

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make setup  # Install dependencies

      - name: Create a release
        run: |
          make release  # Run the 'release' make target
